version: '3.4'

services:
  main_1:
    build: ./
    command: python3 main.py
    restart: always
    deploy:
      resources:
        limits:
          memory: 2Gb
    logging:
      driver: "json-file"
      options:
        max-size: "100m"



#  main_2:
#    build: ./
#    command: python3 main.py
#    restart: always
#
#  main_3:
#    build: ./
#    command: python3 main.py
#    restart: always
#
#  main_4:
#    build: ./
#    command: python3 main.py
#    restart: always
#
#  main_5:
#    build: ./
#    command: python3 main.py
#    restart: always
#
#  main_6:
#    build: ./
#    command: python3 main.py
#    restart: always
#
#  main_7:
#    build: ./
#    command: python3 main.py
#    restart: always